import '../css/common.scss'
import '../css/mainpage.scss'
import '../css/responsive.scss'
import '../css/partnersPage.scss'
import '../css/PM.scss'
import '../css/aboutconatactpage.scss'
import '../css/digitaltwinpage.scss'
import '../css/newspage.scss'
import '../css/termsPolicyPage.scss'

import Head from "next/head";

export default function MyApp({ Component, pageProps }) {
    return <>
        <Head>
            <title>SIMACRO</title>

            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            {/*<script src="https://kit.fontawesome.com/91ff2f5a6d.js" crossOrigin="anonymous"></script>*/}
            {/*<link rel="shortcut icon" href="/SIMACRO_CI.svg" />*/}

        </Head>
        <Component {...pageProps} />
    </>
}